import type { University } from "./types";

// A curated set of real universities across the US, UK and Canada. Acceptance
// rates and costs are real-world approximations for international undergraduates
// (tuition + living, USD/year) and are used only to estimate fit — they are not
// admissions guarantees. minGpa/minIelts are rough competitiveness floors.

export const UNIVERSITIES: University[] = [
  // ── United States ──────────────────────────────────────────────
  {
    id: "mit",
    name: "Massachusetts Institute of Technology",
    country: "US",
    city: "Cambridge, MA",
    fields: ["Computer Science", "Engineering", "Physics & Math", "Economics"],
    acceptanceRate: 4,
    minGpa: 3.95,
    minIelts: 7.0,
    annualCostUSD: 82000,
    blurb: "The global benchmark for STEM. Brutally selective, project-driven, and built for students who live and breathe science.",
  },
  {
    id: "stanford",
    name: "Stanford University",
    country: "US",
    city: "Stanford, CA",
    fields: ["Computer Science", "Engineering", "Business", "Social Sciences"],
    acceptanceRate: 4,
    minGpa: 3.95,
    minIelts: 7.0,
    annualCostUSD: 84000,
    blurb: "Silicon Valley's front door. Entrepreneurial, interdisciplinary, and famously hard to get into.",
  },
  {
    id: "harvard",
    name: "Harvard University",
    country: "US",
    city: "Cambridge, MA",
    fields: ["Law", "Economics", "Medicine & Biology", "Humanities", "Social Sciences"],
    acceptanceRate: 3,
    minGpa: 3.95,
    minIelts: 7.0,
    annualCostUSD: 83000,
    blurb: "The most recognized name in higher education. Deep resources, elite network, single-digit acceptance.",
  },
  {
    id: "cmu",
    name: "Carnegie Mellon University",
    country: "US",
    city: "Pittsburgh, PA",
    fields: ["Computer Science", "Engineering", "Arts & Design", "Business"],
    acceptanceRate: 11,
    minGpa: 3.8,
    minIelts: 7.0,
    annualCostUSD: 80000,
    blurb: "A powerhouse for computer science and a rare place where world-class tech meets fine arts.",
  },
  {
    id: "umich",
    name: "University of Michigan",
    country: "US",
    city: "Ann Arbor, MI",
    fields: ["Engineering", "Business", "Social Sciences", "Medicine & Biology"],
    acceptanceRate: 18,
    minGpa: 3.7,
    minIelts: 6.5,
    annualCostUSD: 70000,
    blurb: "A top public research university with strength across nearly every field and a huge, spirited campus.",
  },
  {
    id: "nyu",
    name: "New York University",
    country: "US",
    city: "New York, NY",
    fields: ["Business", "Arts & Design", "Economics", "Humanities"],
    acceptanceRate: 12,
    minGpa: 3.7,
    minIelts: 7.0,
    annualCostUSD: 85000,
    blurb: "No campus walls — the city is the classroom. A magnet for business, film and the arts.",
  },
  {
    id: "uiuc",
    name: "University of Illinois Urbana-Champaign",
    country: "US",
    city: "Champaign, IL",
    fields: ["Computer Science", "Engineering", "Physics & Math", "Business"],
    acceptanceRate: 45,
    minGpa: 3.5,
    minIelts: 6.5,
    annualCostUSD: 58000,
    blurb: "An engineering and CS heavyweight that is far more attainable than its reputation suggests.",
  },
  {
    id: "psu",
    name: "Pennsylvania State University",
    country: "US",
    city: "University Park, PA",
    fields: ["Engineering", "Business", "Environmental Science", "Social Sciences"],
    acceptanceRate: 55,
    minGpa: 3.3,
    minIelts: 6.5,
    annualCostUSD: 54000,
    blurb: "A large, well-rounded public university with strong industry ties and a famously loyal alumni network.",
  },
  {
    id: "asu",
    name: "Arizona State University",
    country: "US",
    city: "Tempe, AZ",
    fields: ["Business", "Engineering", "Environmental Science", "Arts & Design"],
    acceptanceRate: 88,
    minGpa: 3.0,
    minIelts: 6.0,
    annualCostUSD: 48000,
    blurb: "Innovation-focused and welcoming to international students, with broad programs and accessible admissions.",
  },
  {
    id: "uc-davis",
    name: "University of California, Davis",
    country: "US",
    city: "Davis, CA",
    fields: ["Environmental Science", "Medicine & Biology", "Engineering", "Economics"],
    acceptanceRate: 42,
    minGpa: 3.5,
    minIelts: 7.0,
    annualCostUSD: 66000,
    blurb: "A research leader in life and environmental sciences within the prestigious UC system.",
  },
  {
    id: "northeastern",
    name: "Northeastern University",
    country: "US",
    city: "Boston, MA",
    fields: ["Computer Science", "Business", "Engineering", "Social Sciences"],
    acceptanceRate: 20,
    minGpa: 3.6,
    minIelts: 6.5,
    annualCostUSD: 78000,
    blurb: "Famous for its co-op program — students alternate semesters of study with paid professional placements.",
  },
  {
    id: "purdue",
    name: "Purdue University",
    country: "US",
    city: "West Lafayette, IN",
    fields: ["Engineering", "Computer Science", "Physics & Math", "Environmental Science"],
    acceptanceRate: 50,
    minGpa: 3.4,
    minIelts: 6.5,
    annualCostUSD: 52000,
    blurb: "An engineering institution with a strong value proposition and frozen-tuition affordability.",
  },

  // ── United Kingdom ─────────────────────────────────────────────
  {
    id: "oxford",
    name: "University of Oxford",
    country: "UK",
    city: "Oxford",
    fields: ["Humanities", "Law", "Physics & Math", "Medicine & Biology", "Economics"],
    acceptanceRate: 17,
    minGpa: 3.9,
    minIelts: 7.0,
    annualCostUSD: 60000,
    blurb: "Centuries of tradition and a tutorial system that puts you face-to-face with leading academics.",
  },
  {
    id: "cambridge",
    name: "University of Cambridge",
    country: "UK",
    city: "Cambridge",
    fields: ["Physics & Math", "Engineering", "Medicine & Biology", "Computer Science"],
    acceptanceRate: 16,
    minGpa: 3.9,
    minIelts: 7.5,
    annualCostUSD: 62000,
    blurb: "Oxford's eternal rival and a science colossus, with supervisions in small groups and historic colleges.",
  },
  {
    id: "imperial",
    name: "Imperial College London",
    country: "UK",
    city: "London",
    fields: ["Engineering", "Medicine & Biology", "Computer Science", "Physics & Math"],
    acceptanceRate: 14,
    minGpa: 3.85,
    minIelts: 7.0,
    annualCostUSD: 58000,
    blurb: "A pure STEM and medicine specialist in the heart of London with deep industry connections.",
  },
  {
    id: "ucl",
    name: "University College London",
    country: "UK",
    city: "London",
    fields: ["Arts & Design", "Social Sciences", "Engineering", "Economics", "Law"],
    acceptanceRate: 30,
    minGpa: 3.7,
    minIelts: 6.5,
    annualCostUSD: 55000,
    blurb: "London's broad, research-intensive university — strong in almost everything and famously global.",
  },
  {
    id: "lse",
    name: "London School of Economics",
    country: "UK",
    city: "London",
    fields: ["Economics", "Social Sciences", "Law", "Business"],
    acceptanceRate: 25,
    minGpa: 3.8,
    minIelts: 7.0,
    annualCostUSD: 56000,
    blurb: "The world's social-science specialist — economics, politics and finance taught at the highest level.",
  },
  {
    id: "edinburgh",
    name: "University of Edinburgh",
    country: "UK",
    city: "Edinburgh",
    fields: ["Computer Science", "Humanities", "Medicine & Biology", "Environmental Science"],
    acceptanceRate: 40,
    minGpa: 3.5,
    minIelts: 6.5,
    annualCostUSD: 48000,
    blurb: "A historic Scottish university with global standing and a vibrant, walkable festival city.",
  },
  {
    id: "manchester",
    name: "University of Manchester",
    country: "UK",
    city: "Manchester",
    fields: ["Engineering", "Business", "Physics & Math", "Social Sciences"],
    acceptanceRate: 56,
    minGpa: 3.3,
    minIelts: 6.5,
    annualCostUSD: 42000,
    blurb: "A large, diverse research university where the atom was first split — strong and welcoming to internationals.",
  },
  {
    id: "glasgow",
    name: "University of Glasgow",
    country: "UK",
    city: "Glasgow",
    fields: ["Law", "Engineering", "Humanities", "Medicine & Biology"],
    acceptanceRate: 65,
    minGpa: 3.2,
    minIelts: 6.5,
    annualCostUSD: 40000,
    blurb: "One of the UK's oldest universities, combining tradition with accessible international admissions.",
  },

  // ── Canada ─────────────────────────────────────────────────────
  {
    id: "toronto",
    name: "University of Toronto",
    country: "Canada",
    city: "Toronto, ON",
    fields: ["Computer Science", "Medicine & Biology", "Engineering", "Economics"],
    acceptanceRate: 43,
    minGpa: 3.7,
    minIelts: 6.5,
    annualCostUSD: 52000,
    blurb: "Canada's top research university and an AI research pioneer, set in a global, multicultural city.",
  },
  {
    id: "ubc",
    name: "University of British Columbia",
    country: "Canada",
    city: "Vancouver, BC",
    fields: ["Environmental Science", "Computer Science", "Business", "Arts & Design"],
    acceptanceRate: 52,
    minGpa: 3.6,
    minIelts: 6.5,
    annualCostUSD: 48000,
    blurb: "A stunning coastal campus, sustainability leadership, and broad strength across the sciences and arts.",
  },
  {
    id: "mcgill",
    name: "McGill University",
    country: "Canada",
    city: "Montreal, QC",
    fields: ["Medicine & Biology", "Law", "Engineering", "Humanities"],
    acceptanceRate: 46,
    minGpa: 3.7,
    minIelts: 6.5,
    annualCostUSD: 45000,
    blurb: "Often called 'Canada's Harvard,' with a strong international reputation and a lively, affordable city.",
  },
  {
    id: "waterloo",
    name: "University of Waterloo",
    country: "Canada",
    city: "Waterloo, ON",
    fields: ["Computer Science", "Engineering", "Physics & Math", "Business"],
    acceptanceRate: 53,
    minGpa: 3.6,
    minIelts: 6.5,
    annualCostUSD: 47000,
    blurb: "The co-op capital of Canada — a tech and engineering feeder famous for its work-integrated programs.",
  },
  {
    id: "mcmaster",
    name: "McMaster University",
    country: "Canada",
    city: "Hamilton, ON",
    fields: ["Medicine & Biology", "Engineering", "Business", "Social Sciences"],
    acceptanceRate: 58,
    minGpa: 3.4,
    minIelts: 6.5,
    annualCostUSD: 43000,
    blurb: "A health-sciences and engineering leader pioneering problem-based, hands-on learning.",
  },
  {
    id: "alberta",
    name: "University of Alberta",
    country: "Canada",
    city: "Edmonton, AB",
    fields: ["Engineering", "Environmental Science", "Medicine & Biology", "Physics & Math"],
    acceptanceRate: 60,
    minGpa: 3.3,
    minIelts: 6.5,
    annualCostUSD: 38000,
    blurb: "Strong in energy, engineering and sciences, with comparatively affordable tuition and living costs.",
  },
  {
    id: "western",
    name: "Western University",
    country: "Canada",
    city: "London, ON",
    fields: ["Business", "Medicine & Biology", "Law", "Social Sciences"],
    acceptanceRate: 65,
    minGpa: 3.3,
    minIelts: 6.5,
    annualCostUSD: 42000,
    blurb: "Known for its Ivey Business School and a classic, picturesque campus experience.",
  },
  {
    id: "simon-fraser",
    name: "Simon Fraser University",
    country: "Canada",
    city: "Burnaby, BC",
    fields: ["Computer Science", "Business", "Environmental Science", "Arts & Design"],
    acceptanceRate: 70,
    minGpa: 3.1,
    minIelts: 6.0,
    annualCostUSD: 36000,
    blurb: "An innovative, co-op-friendly university near Vancouver with accessible admissions for internationals.",
  },
];
